name: inceptor_flutter
description: Flutter SDK for Inceptor crash logging service. Automatically captures and reports crashes and errors from your Flutter application.
version: 1.0.0
homepage: https://github.com/flakerimi/inceptor
repository: https://github.com/flakerimi/inceptor
issue_tracker: https://github.com/flakerimi/inceptor/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  device_info_plus: ^9.1.0
  package_info_plus: ^5.0.1
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  # This package does not include any assets
